-- إضافة حقول تحليل الورديات (تقسيم الأيام والليل/النهار)
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS spans_multiple_days BOOLEAN DEFAULT FALSE;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS day_one_date TIMESTAMPTZ;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS day_two_date TIMESTAMPTZ;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS day_one_hours DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS day_two_hours DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS night_hours DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS day_hours DOUBLE PRECISION;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS is_night_shift BOOLEAN DEFAULT FALSE;
